-- RIVER Supabase schema
-- Run this in Supabase Dashboard > SQL Editor for project vpeomywcwjijxdkhgqnn.
-- Contact details are private: public clients can INSERT requests but cannot SELECT them.
create extension if not exists pgcrypto;

create table if not exists public.river_events (
  id bigint generated by default as identity primary key,
  name text not null,
  event_date timestamptz,
  description text not null default '',
  status text not null default 'open' check (status in ('open','closed','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.river_players (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  points integer not null default 0,
  games_played integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.river_requests (
  id uuid primary key default gen_random_uuid(),
  player_name text not null,
  phone text not null,
  telegram text not null,
  event_id bigint references public.river_events(id) on delete set null,
  message text not null default '',
  status text not null default 'new' check (status in ('new','contacted','confirmed','declined')),
  created_at timestamptz not null default now()
);

create table if not exists public.river_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.river_site_content (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.river_events enable row level security;
alter table public.river_players enable row level security;
alter table public.river_requests enable row level security;
alter table public.river_settings enable row level security;
alter table public.river_site_content enable row level security;

-- Public visitors may see public events and leaderboard, but not contact details.
drop policy if exists "Public can read events" on public.river_events;
create policy "Public can read events" on public.river_events for select to anon, authenticated using (true);

drop policy if exists "Public can read leaderboard" on public.river_players;
create policy "Public can read leaderboard" on public.river_players for select to anon, authenticated using (true);

-- A public signup form may submit requests. No public SELECT/UPDATE/DELETE policies are created.
drop policy if exists "Visitors can submit signup requests" on public.river_requests;
create policy "Visitors can submit signup requests" on public.river_requests for insert to anon, authenticated
with check (
  length(trim(player_name)) between 2 and 100
  and length(trim(phone)) between 7 and 30
  and length(trim(telegram)) between 3 and 100
  and status = 'new'
);

-- Settings and editable site content are intentionally private by default.
-- Admin access should be performed through a trusted server/Edge Function or authenticated
-- admin role with explicit policies. Never put a service_role key in index.html.
